### ISSUE TITLE
Integracón del response_format a los lineamientos del OAS

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/lineamientos_oas#2]
Viendo que se puede optimizar y separar procesos en el format de las respuestas Json de los APIs, se propuso el response_format, el cual es un interceptor que toma los datos salientes y los formatea en un json evitando la modificación manual del código . Funciona de forma independiente a beego, y sus respuestas son configurables.

Doc en Util_oas de su uso, se planea integrar su uso en los lineamientos de este repositorio.
[Link a Documentación](https://github.com/udistrital/utils_oas/tree/master/responseformat).
_Aporte de @miguelramirez93_ 

Tras la reunión del día de hoy con J quien protege la seguridad en los sistemas y los arquitectos Jhon y Jairo, se planteo hacer una pruebas y dejar un link en el que pueda tambien hacer sus pruebas, para finalizar la aprobación como nuevo lineamiento.

**Comment by jjvargass** [comment]
Se  Solicita endpoint para realizar las pruebas.

**Comment by Soulfilip-UD** [comment]
Endpoint : http://10.20.0.254:8201/v1/rubro

**Comment by jjvargass** [comment]
Se han realizado las pruebas al API, por favor revisar el documento que se ha compartido con nombre **Financiera Pruebas Respuestas Json V-1.0**

**Comment by Soulfilip-UD** [comment]
El Documento se reviso, se tendra en cuenta todas las recomendaciones . Para una segunda revisión

**Comment by AlexFBP** [comment]
Tomando como referencia
1. Que Beego sirve para generar REST APIs 
2. Que una API REST trabaja directamente sobre HTTP
3. Que HTTP tiene más que suficientes [códigos de estado](https://developer.mozilla.org/es/docs/Web/HTTP/Status) para la mayoría de las situaciones, e inclusive tiene estados genéricos (x00)
4. Que Beego [genera documentación OpenAPI (swagger)](https://beego.me/docs/advantage/docs.md) a partir de la descripción que se coloca antes de cada controlador, y entre otras cosas, permite documentar no sólamente lo que espera/retorna una petición determinada, sino también qué significa cada código de respuesta
5. Que TODO cliente HTTP (bien sea un navegador o un MID), por protocolo; siempre va a tener a su disposición el código de respuesta de cada petición HTTP realizada, y por tanto puede operar en función de este código de respuesta. Lo cual es evidente incluso con las herramientas de desarrollo disponibles en el navegador, cuando se va a la sección de Red; o con un cliente dedicado a probar clientes HTTP como [postman](https://www.postman.com/) o [insomnia](https://insomnia.rest/products/insomnia)
6. _"Si se sabe con certeza que un mensaje va a ser recibido, su cantidad de información es cero"_ de acuerdo a la [teoría de la información de Shanon/Webber](https://es.wikipedia.org/wiki/Teor%C3%ADa_de_la_informaci%C3%B3n), la cantidad de información de un mensaje que no cambia, que siempre se espera en determinadas condiciones; es cero, lo cual en otras palabras implica que transmitir dicha información es únicamente un desperdicio de recursos, y este es el principio de existencia/funcionamiento de los algoritmos de compresión empleados para audio, video, broadcasting web, TDT, etc.: quitar la información repetida en tiempo/espacio

Planteo/Pregunto:
1. Si Beego permite establecer arbitrariamente el valor del código de respuesta HTTP, por qué la necesidad de "reinventar la rueda" encapsulando la respuesta en una estructura adicional? Tener que especificar el código de estado en dos lugares no solo da pie a ambigüedad sino que al ir también en el cuerpo de la respuesta, la cantidad de información de ese código "redundante" es cero
2. Siempre que la petición sea exitosa (2xx), del mensaje encapsulado la única propiedad con información va a ser `"Data"`, las demás propiedades ni se usan/leen porque su información no cambia o se considera irrelevante, y por tanto su cantidad de información es nula.
3. Cuando una petición sea fallida (4xx/5xx), no debería esperarse información confiable en `"Data"` sino en las demás propiedades de la respuesta encapsulada (y eso, por máximo, porque debería de bastar con el código de estado)
4. En ambos casos (exito/error), hay un código de respuesta repetido, tanto por protocolo como en el cuerpo de la respuesta, por tanto la información del campo `"Status"` en el cuerpo de la respuesta, es nula. (por protocolo, no se puede quitar el código de respuesta que va en el protocolo)
5. Para peticiones exitosas, se puede enviar la data sin encapsular, y para peticiones erróneas, se puede enviar de vuelta el mensaje encapsulado. Inclusive, el cuerpo de las peticiones erróneas podría ser el mismo mensaje de error que se va a imprimir en los logs del API
6. Se puede tomar como lineamiento, no solamente seguir el actual lineamiento de control de errores, sino también actualizar juiciosamente los comentarios a los controladores para que Beego genere la documentación swagger automáticamente, lo que a su vez facilita la integración con WSO2
