### ISSUE TITLE
Propuesta del plan de trabajo (Código QR)

### ISSUE THREAD

**Issue by a52290451** [udistrital/lineamientos_oas#34]
Proponer el plan de trabajo correspondiente al requerimiento:

-  Diseñar e implementar los componentes de autenticación documental electrónica (Pagina de alternancia con código QR).

De igual forma, asignar prioridad a cada item, así como el orden en que se deben abordar.

**Criterios de aceptación**

- [x] Documento con la propuesta de trabajo realizada (Formato del documento libre).

**Comment by FelipeVel** [comment]
[Propuesta de plan de trabajo](https://drive.google.com/file/d/1Wy3hXI1KZraxD4PnyOLsFoXHiiwyE7YI/view?usp=sharing)

Se agendará reunión con @corio27 para la validación y posteriormente dar inicio al desarrollo.

**Comment by FelipeVel** [comment]
Se solicita un usuario de prueba que contenga información en la base de datos de terceros de core, para poder hacer las pruebas de la funcionalidad QR en el aplicativo de alternancia.

Para las pruebas se autorizó modificar la base de datos para que el usuario tenga información registrada y se puedan hacer las pruebas.

**Comment by a52290451** [comment]
Se aprueba propuesta del plan de trabajo, adicionando los siguientes requerimientos:

- Se debe realizar el conteo de códigos QR escaneados al momento de ingresar a la sede, y al momento de ingresar a un salón de clases.
- Se debe registrar la salida de estudiantes de la sede.

Se adjunta [link de la grabación](https://drive.google.com/file/d/1DqLjrSCQ3ZZrv_qHkyovOsrQsVz-GWlm/view?usp=sharing) de la reunión.
