### ISSUE TITLE
Apropiación de generalidades

### ISSUE THREAD

**Issue by a52290451** [udistrital/lineamientos_oas#35]
Asimilar el funcionamiento general del sistema a trabajar, así como de su flujo y acciones necesarias por implementar, de acuerdo a las siguientes actividades:

- [x] Revisión e instalación de repositorios.
- [x] Revisión de documentación relacionada. (CORE)
- [x] Análisis de requerimientos.

**Criterios de aceptación**

- [x] Registrar el estado actual en el que se recibe el sistema para las funcionalidad específica a implementar (Elaboración propia).
- [x] Registrar inquietudes respecto a los requerimientos analizados.

**Nota**: Se contempla reunión para capacitación en Frameworks antiguos de PHP.

**Comment by criss201x** [comment]
Se realizaron las siguientes actividades:

- Configuración del ambiente de desarrollo para sistemas en desarrollo.
- Revisión y análisis de la documentación y grabaciones del grupo CORE 2021.
- Se realiza un diagnostico de los diferentes sistemas relacionados a los requerimientos del objeto contractual.

se adjunta documento de análisis completo, disponible [aquí](https://docs.google.com/document/d/1hg7ew3O6GMUtrA8y6bNRvWgsmNeiW4k5roDcbIbwk9A/edit?usp=sharing).
