### ISSUE TITLE
Investigación para desarrollo de funcionalidades (Firma Electrónica y Actualización de autenticación en sistemas antiguos)

### ISSUE THREAD

**Issue by a52290451** [udistrital/lineamientos_oas#36]
Se requiere realizar investigación acerca de posibles alternativas de solución para cubrir los siguientes requerimientos:

1. Ajustar y/o implementar el sistema de autenticación única.
2. Implementar servicio de firma electrónica.

**Criterios de aceptación**

- [x] Registro de la actividad investigativa para cada requerimiento.
- [x] Propuestas de solución para cada requerimiento.

**Comment by criss201x** [comment]
Se realiza análisis técnico para la implementacion de un sistema de firma electrónica, donde se investigan los diferentes mecanismos, estándares, normatividad y tipos de firma electrónica, con el fin de delimitar el alcance del desarrollo a realizar, en el análisis se plantearon las siguientes tecnologías:
- NODE-SIGNPDF
- SIGNSERVER
- PYHANKO
- ENDESIVE

Estas tecnologías son opensource y se podrían implementar desde un servicio MID como cualquier otro dentro de la organización, se adjunta documentación referente a la investigación realizada.

- Documento de análisis completo, disponible [aquí](https://docs.google.com/document/d/1kjyf8pTP_vy5kSSVaYYIYG7yGbKOrUAhMiGuvLy_nbo/edit?usp=sharing). 
- Presentación de la propuesta, disponible [aquí](https://docs.google.com/presentation/d/1tPKIGT3NB54yIjxoB5z5PQCCIbcy4BK7n1fUh4R3s9Q/edit?usp=sharing).

**Comment by criss201x** [comment]
link de la reunión de la presentación de la propuesta, [aquí](https://drive.google.com/file/d/1c_eUYH0NhN7E6HYiszTDcGA3grqUJ6u1/view?usp=sharing).
