### ISSUE TITLE
Investigación Fase 2 acerca del desarrollo de Firma Electrónica en documentos de la OAS

### ISSUE THREAD

**Issue by a52290451** [udistrital/lineamientos_oas#38]
De acuerdo a la investigación realizada en el issue #36, se requiere complementar dicha investigación y proponer alternativas de solución para implementar un metodo de firma electrónica en documentos de la OAS que será lineamiento para todos los sistemas.

**Criterios de aceptación**

- [x] Documento de investigación realizada.
- [x] Presentación de la investigación y soluciones propuestas.

**Comment by iMrJulian** [comment]
Investigación y análisis de la implantación de la firma electrónica con respecto a lo dispuesto por la ley Colombiana para su validez jurídica

Documento :https://docs.google.com/document/d/1DIbO4ElV7vmHyV4MdNhmMk1ZWUA7eNhHIKxQ24F_dy8/edit?usp=sharing
Presentación: https://docs.google.com/presentation/d/1PIw7om-Er6HUfBYkSNo3FbSBKxFR2srXNri6CLWQ9zM/edit?usp=sharing
